### ISSUE TITLE
CoinMarketCap Rate limiting 

### ISSUE THREAD

**Issue by b-zig** [bonovoxly/coinmarketcap-exporter#16]
What's the best way to rate limit the API hits against CoinMarketCap? 

I'm on the free tier which has max 333 API hits in a 24hr period. 

I've reduced cache to 50, cache TTL to 10 and have also removed metrics not required.

**Comment by b-zig** [comment]
Figured it out... I was thinking less cache = lower limit. However it only made things worse! found a medium which keeps me within limits. 

Thanks yall

**Comment by bonovoxly** [comment]
Glad it worked out for you!

**Comment by Robin-Sch** [comment]
> Figured it out... I was thinking less cache = lower limit. However it only made things worse! found a medium which keeps me within limits.
> 
> Thanks yall

you mind sharing?
