### ISSUE TITLE
Prometheus doesn't like the exporter

### ISSUE THREAD

**Issue by scumola** [bonovoxly/coinmarketcap-exporter#4]
I'm seeing:
text format parsing error in line 1670: second HELP line for metric name "coin_market"

when prometheus parses the output of the exporter.  I think that there's more than one definitions of "coin_market" in many different HELP/TYPE lines.  I think that it only needs/wants one.

```
root@prometheus:/etc/prometheus# curl -s http://10.0.0.23:9101/metrics | grep " coin_market " | head -n 6
# HELP coin_market coinmarketcap metric values
# TYPE coin_market gauge
# HELP coin_market coinmarketcap metric values
# TYPE coin_market gauge
# HELP coin_market coinmarketcap metric values
# TYPE coin_market gauge
```

**Comment by bonovoxly** [comment]
I'll work on fixing this up.

**Comment by bonovoxly** [comment]
Closing this, moving discussion here:

https://github.com/bonovoxly/coinmarketcap-exporter/issues/5#issuecomment-561216660

**Comment by bonovoxly** [comment]
Resolved via https://github.com/bonovoxly/coinmarketcap-exporter/pull/7/
